### ISSUE TITLE
kid claim fuzzing

### ISSUE THREAD

**Issue by adefirmant** [pinnace/burp-jwt-fuzzhelper-extension#5]
Hi, i need more guidance in kid claim fuzzing, especially in signing key from a file.
I am windows user, what is the right way to write the "path to signing key"

For example:
file name site.css located in C:\key\site.css
Should i write "C:\key\site.css"
or I should move the "site.css" file in same folder with the Burp and just write "./site.css" as a path or what?

I raise this issue because I have already tried the right path traversal, but it always returned "invalid signature"

**Comment by pinnace** [comment]
Hey @adefirmant 

Though I have not tested this on Windows, it should work fine. The path you submit is just passed to Python's open() function and .read() from. I advise you use a Windows style absolute path with backslashes escaped (i.e. C:\\key\\site.css) or trying the more portable C:/key/site.css, which should work. Let me know if this is successful, and I will update the readme.
